# Site settings
title: 50 Years Later
subhead: Five decades after the UT Tower shooting, The Daily Texan remembers those involved in the 96 minutes that changed the University forever.
email: juntan@utexas.edu
description: A Daily Texan feature story.
baseurl: "/features/tower" # the subpath of your site, e.g. /blog/
url: "http://dailytexanonline.com" # the base hostname & protocol for your site
twitter: thedailytexan
facebook: dailytexan

# Build settings
markdown: kramdown
sass:
  style: compressed


# Output

permalink: /:title.html